name: PersistentGrowth
main: com.civclassic.persistentgrowth.PersistentGrowth
version: ${project.version}
depend: [CivModCore]
commands:
  persistentgrowth:
    description: Reloads PersistentGrowth
    usage: "Usage: /persistentgrowth"
    permission: persistentgrowth.admin
permissions:
  persistentgrowth.admin:
    description: Allows usage of persistentgrowth command
    default: op