name: PersistentGrowth
main: com.civclassic.persistentgrowth.PersistentGrowth
version: ${project.version}
depend: [CivModCore]
commands:
  persistentgrowth:
    description: Reloads PersistentGrowth
    usage: "Usage: /persistentgrowth"
    permission: op